export const pokemones = [
    { name: "Blaziken", rol: "equilibrado", ex: false },
    { name: "Falinks", rol: "equilibrado", ex: false },
    { name: "Gyarados", rol: "equilibrado", ex: false },
    { name: "Inteleon", rol: "atacante", ex: false },
    { name: "Leafeon", rol: "agil", ex: false },
    { name: "Meowscarada", rol: "agil", ex: false },
    { name: "Metagross", rol: "equilibrado", ex: false },
    { name: "Mewtwo", rol: "equilibrado", ex: true },
    { name: "Mimikyu", rol: "equilibrado", ex: false },
    { name: "Miraidon", rol: "atacante", ex: true },

    { name: "Umbreon", rol: "defensivo", ex: false },
    { name: "Chandelure", rol: "atacante", ex: false },
    { name: "Lapras", rol: "defensivo", ex: false },
    { name: "Goodra", rol: "defensivo", ex: false },
    { name: "Zacian", rol: "equilibrado", ex: true },
    { name: "Comfey", rol: "soporte", ex: false },
    { name: "Dragapult", rol: "atacante", ex: false },
    { name: "Urshifu", rol: "equilibrado", ex: false },
    { name: "Sableye", rol: "soporte", ex: false },
    { name: "Zoroark", rol: "agil", ex: false },
    { name: "Clefable", rol: "soporte", ex: false },
    { name: "Scizor", rol: "equilibrado", ex: false },
    { name: "Dodrio", rol: "agil", ex: false },
    { name: "Mew", rol: "atacante", ex: false },
    { name: "Tyranitar", rol: "equilibrado", ex: false },
    { name: "Buzzwole", rol: "equilibrado", ex: false },
    { name: "Glaceon", rol: "atacante", ex: false },
    { name: "Delphox", rol: "atacante", ex: false },
    { name: "Espeon", rol: "atacante", ex: false },
    { name: "Azumarill", rol: "equilibrado", ex: false }
]