export const base_pokemones = [
    { name: "Blaziken", rol: "equilibrado", ex: false },
    { name: "Falinks", rol: "equilibrado", ex: false },
    { name: "Gyarados", rol: "equilibrado", ex: false },
    { name: "Inteleon", rol: "atacante", ex: false },
    { name: "Leafeon", rol: "agil", ex: false },
    { name: "Meowscarada", rol: "agil", ex: false },
    { name: "Metagross", rol: "equilibrado", ex: false },
    { name: "Mewtwo", rol: "equilibrado", ex: true },
    { name: "Mimikyu", rol: "equilibrado", ex: false },
    { name: "Miraidon", rol: "atacante", ex: true },

    { name: "Umbreon", rol: "defensivo", ex: false },
    { name: "Chandelure", rol: "atacante", ex: false },
    { name: "Lapras", rol: "defensivo", ex: false },
    { name: "Goodra", rol: "defensivo", ex: false },
    { name: "Zacian", rol: "equilibrado", ex: true },
    { name: "Comfey", rol: "auxiliar", ex: false },
    { name: "Dragapult", rol: "atacante", ex: false },
    { name: "Urshifu", rol: "equilibrado", ex: false },
    { name: "Sableye", rol: "auxiliar", ex: false },
    { name: "Zoroark", rol: "agil", ex: false },
    { name: "Clefable", rol: "auxiliar", ex: false },
    { name: "Scizor", rol: "equilibrado", ex: false },
    { name: "Dodrio", rol: "agil", ex: false },
    { name: "Mew", rol: "atacante", ex: false },
    { name: "Tyranitar", rol: "equilibrado", ex: false },
    { name: "Buzzwole", rol: "equilibrado", ex: false },
    { name: "Glaceon", rol: "atacante", ex: false },
    { name: "Delphox", rol: "atacante", ex: false },
    { name: "Espeon", rol: "atacante", ex: false },
    { name: "Azumarill", rol: "equilibrado", ex: false },

    { name: "Ceruledge", rol: "equilibrado", ex: false },
    { name: "Ho oh", rol: "defensivo", ex: true },
    { name: "Darkrai", rol: "agil", ex: false },
    { name: "Psyduck", rol: "auxiliar", ex: false },
    { name: "Tinkaton", rol: "equilibrado", ex: false },
    { name: "Armarouge", rol: "atacante", ex: false },
    { name: "Duraludon", rol: "atacante", ex: false },
    { name: "Hoopa", rol: "auxiliar", ex: false },
    { name: "Aegislash", rol: "equilibrado", ex: false },
    { name: "Trevenant", rol: "defensivo", ex: false },
    { name: "Dragonite", rol: "equilibrado", ex: false },
    { name: "Tsareena", rol: "equilibrado", ex: false },
    { name: "Mamoswine", rol: "defensivo", ex: false },
    { name: "Decidueye", rol: "atacante", ex: false },
    { name: "Greedent", rol: "defensivo", ex: false },
    { name: "Sylveon", rol: "atacante", ex: false },
    { name: "Blastoise", rol: "defensivo", ex: false },
    { name: "Blissey", rol: "auxiliar", ex: false },
    { name: "Gardevoir", rol: "atacante", ex: false },
    { name: "Zeraora", rol: "agil", ex: false },
    { name: "Pikachu", rol: "atacante", ex: false },
    { name: "Charizard", rol: "equilibrado", ex: false },
    { name: "Snorlax", rol: "defensivo", ex: false },
    { name: "Crustle", rol: "defensivo", ex: false },
    { name: "Greninja", rol: "atacante", ex: false },
    { name: "Eldegoss", rol: "auxiliar", ex: false },
    { name: "Talonflame", rol: "agil", ex: false },
    { name: "Lucario", rol: "equilibrado", ex: false },
    { name: "Venusaur", rol: "atacante", ex: false },
    { name: "Mr Mime", rol: "auxiliar", ex: false },
    { name: "Slowbro", rol: "defensivo", ex: false },
    { name: "Absol", rol: "agil", ex: false },
    { name: "Machamp", rol: "equilibrado", ex: false },
    { name: "Wigglytuff", rol: "auxiliar", ex: false },
    { name: "Ninetales Alola", rol: "atacante", ex: false },
    { name: "Cramorant", rol: "atacante", ex: false },
    { name: "Gengar", rol: "agil", ex: false },
    { name: "Garchomp", rol: "equilibrado", ex: false },
    { name: "Cinderace", rol: "atacante", ex: false },
]